version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_DB: challengeDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lombab56
  cache:
    image: redis
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  app:
    build: ./
    ports:
      - "9070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/challengeDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lombab56
      SPRING_REDIS_HOST: 127.0.0.1
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - cache
